name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t laizn-ai-backend:latest .

      - name: Save Docker image to tar
        run: |
          docker save -o laizn-ai-backend.tar laizn-ai-backend:latest

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload Docker image tar to remote server via rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" laizn-ai-backend.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/

      - name: Load Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker load -i /tmp/laizn-ai-backend.tar && rm /tmp/laizn-ai-backend.tar"

      - name: Upload docker-compose file to remote server via rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" deploy/docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.REMOTE_DEPLOY_DIR }}/

      - name: Deploy application via docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd ${{ secrets.REMOTE_DEPLOY_DIR }} && docker-compose down && docker-compose up -d"
